import { faker } from '@faker-js/faker';
import * as fs from 'fs';
import * as path from 'path';

// Generate repeatable data
faker.seed(123);

const CITIES = [
  { name: 'New York', lat: 40.7128, lng: -74.0060 },
  { name: 'Los Angeles', lat: 34.0522, lng: -118.2437 },
  { name: 'Chicago', lat: 41.8781, lng: -87.6298 },
  { name: 'Houston', lat: 29.7604, lng: -95.3698 },
  { name: 'Phoenix', lat: 33.4484, lng: -112.0740 }
];

const CUSTOMER_COUNT = 50;
const DRIVER_COUNT = 20;
const MERCHANT_COUNT = 20;
const PRODUCTS_PER_MERCHANT = 10;
const ORDER_COUNT = 100;

function generateId() {
  return faker.string.uuid();
}

const customers: string[] = [];
const drivers: string[] = [];
const merchants: string[] = [];

let sql = `-- OneMove MVP Seed Data
-- Auto-generated by scripts/generate-seed.ts
-- DO NOT EDIT DIRECTLY

-- Disable Triggers temporarily
SET session_replication_role = 'replica';

`;

// 1. Generate Auth Users and Profiles
sql += `-- Auth Users & Profiles\n`;

function createUser(role: string, index: number) {
  const id = generateId();
  const email = `${role}${index}@example.com`;
  const name = faker.person.fullName();
  
  // Auth User (Simulated for Supabase)
  sql += `INSERT INTO auth.users (id, email, raw_user_meta_data, created_at, updated_at) VALUES ('${id}', '${email}', '{"name":"${name}"}', NOW(), NOW());\n`;
  
  // Profile
  sql += `INSERT INTO profiles (id, role, full_name, phone, created_at, updated_at) VALUES ('${id}', '${role}', '${name}', '${faker.phone.number()}', NOW(), NOW());\n`;
  
  return id;
}

for (let i = 0; i < CUSTOMER_COUNT; i++) customers.push(createUser('customer', i));
for (let i = 0; i < DRIVER_COUNT; i++) drivers.push(createUser('driver', i));
for (let i = 0; i < MERCHANT_COUNT; i++) merchants.push(createUser('merchant', i));

// 2. Generate Vehicles for Drivers
sql += `\n-- Vehicles\n`;
drivers.forEach(driverId => {
  const vType = faker.helpers.arrayElement(['car', 'bike', 'scooter']);
  sql += `INSERT INTO vehicles (driver_id, make, model, plate_number, color, type) VALUES ('${driverId}', '${faker.vehicle.manufacturer()}', '${faker.vehicle.model()}', '${faker.vehicle.vrm()}', '${faker.vehicle.color()}', '${vType}');\n`;
  
  // Also initialize tracking
  const city = faker.helpers.arrayElement(CITIES);
  const lat = city.lat + faker.number.float({ min: -0.1, max: 0.1 });
  const lng = city.lng + faker.number.float({ min: -0.1, max: 0.1 });
  sql += `INSERT INTO tracking (driver_id, is_online, current_location) VALUES ('${driverId}', true, '{"lat": ${lat}, "lng": ${lng}, "heading": ${faker.number.int({min: 0, max: 360})}}');\n`;
});

// 3. Generate Merchants and Products
sql += `\n-- Merchants & Products\n`;
const merchantIds: string[] = [];

merchants.forEach(ownerId => {
  const id = generateId();
  merchantIds.push(id);
  const city = faker.helpers.arrayElement(CITIES);
  const lat = city.lat + faker.number.float({ min: -0.05, max: 0.05 });
  const lng = city.lng + faker.number.float({ min: -0.05, max: 0.05 });
  const category = faker.helpers.arrayElement(['restaurant', 'grocery', 'retail']);
  const name = faker.company.name() + (category === 'restaurant' ? ' Cafe' : ' Mart');
  
  sql += `INSERT INTO merchants (id, owner_id, name, description, category, status, rating, address_line1, latitude, longitude) VALUES ('${id}', '${ownerId}', '${name.replace(/'/g, "''")}', '${faker.company.catchPhrase().replace(/'/g, "''")}', '${category}', 'active', ${faker.number.float({ min: 3.5, max: 5.0, fractionDigits: 2 })}, '${faker.location.streetAddress().replace(/'/g, "''")}', ${lat}, ${lng});\n`;

  // Products
  const productIdsForMerchant: string[] = [];
  for (let i = 0; i < PRODUCTS_PER_MERCHANT; i++) {
    const prodId = generateId();
    productIdsForMerchant.push(prodId);
    sql += `INSERT INTO products (id, merchant_id, name, description, price, is_available) VALUES ('${prodId}', '${id}', '${faker.commerce.productName().replace(/'/g, "''")}', '${faker.commerce.productDescription().replace(/'/g, "''")}', ${faker.commerce.price({ min: 5, max: 100 })}, true);\n`;
  }
});

// 4. Generate Orders
sql += `\n-- Orders & Payments\n`;
for (let i = 0; i < ORDER_COUNT; i++) {
  const orderId = generateId();
  const customerId = faker.helpers.arrayElement(customers);
  const driverId = faker.datatype.boolean() ? faker.helpers.arrayElement(drivers) : 'NULL';
  const serviceType = faker.helpers.arrayElement(['ride', 'eats', 'grocery', 'courier']);
  const status = faker.helpers.arrayElement(['pending', 'accepted', 'in_transit', 'completed', 'cancelled']);
  const amount = faker.number.float({ min: 10, max: 150, fractionDigits: 2 });
  
  const city = faker.helpers.arrayElement(CITIES);
  const pLat = city.lat + faker.number.float({ min: -0.05, max: 0.05 });
  const pLng = city.lng + faker.number.float({ min: -0.05, max: 0.05 });
  const dLat = city.lat + faker.number.float({ min: -0.05, max: 0.05 });
  const dLng = city.lng + faker.number.float({ min: -0.05, max: 0.05 });
  
  const pickup = `{"lat": ${pLat}, "lng": ${pLng}, "address": "${faker.location.streetAddress().replace(/'/g, "")}"}`;
  const dropoff = `{"lat": ${dLat}, "lng": ${dLng}, "address": "${faker.location.streetAddress().replace(/'/g, "")}"}`;
  
  let merchantIdStr = 'NULL';
  if (serviceType === 'eats' || serviceType === 'grocery') {
    merchantIdStr = `'${faker.helpers.arrayElement(merchantIds)}'`;
  }
  
  const driverStr = driverId === 'NULL' ? 'NULL' : `'${driverId}'`;

  sql += `INSERT INTO orders (id, customer_id, merchant_id, driver_id, service_type, status, total_amount, pickup_location, dropoff_location) VALUES ('${orderId}', '${customerId}', ${merchantIdStr}, ${driverStr}, '${serviceType}', '${status}', ${amount}, '${pickup}', '${dropoff}');\n`;
  
  // Payment
  const payStatus = status === 'completed' ? 'succeeded' : (status === 'cancelled' ? 'refunded' : 'pending');
  sql += `INSERT INTO payments (order_id, customer_id, amount, status) VALUES ('${orderId}', '${customerId}', ${amount}, '${payStatus}');\n`;
}

sql += `\n-- Restore Triggers\nSET session_replication_role = 'origin';\n`;

fs.writeFileSync(path.join(process.cwd(), 'supabase', 'seed.sql'), sql);
console.log('Successfully generated supabase/seed.sql');
