from enum import Enum


class Provenance(str, Enum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    ESTIMATED = "ESTIMATED"
    SIMULATED = "SIMULATED"
    PUBLIC_BENCHMARK = "PUBLIC_BENCHMARK"
    MERCHANT_CONFIDENTIAL = "MERCHANT_CONFIDENTIAL"
    DEMO_SYNTHETIC = "DEMO_SYNTHETIC"
    ASSUMPTION = "ASSUMPTION"
